# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Roel.io
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Over online ontwikkelingen, fotografie,
  privacy en meer!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://roel.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: roelgroeneveld
github_username:  roelgroeneveld

#paginate: 2

# Build settings
markdown: kramdown
theme: tale
paginate: 5
permalink: /posts/:slug

# theme: minima
# theme: jekyll-theme-lanyon
plugins:
  - jekyll-feed
#  - jekyll-paginate
#  - jekyll-optional-front-matter
#  - jekyll-default-layout
#  - jekyll-titles-from-headings



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
